# Figure 5

## Cx43 (encoded by gene GJA1) in bone lesions versus orthotopic tumors
The analysis is based on GSE110451.

```{r}
boxplot(human_count_gene["GJA1",] ~ human_count.ann$type)
title(main="CX43")
t.test(human_count_gene["GJA1",] ~ human_count.ann$type)
```


# Figure S5

## Metastasis-free survival curve
This analysis is based on a combined Erasmus/MSKCC dataset (GSE2603, 5327, 2034, and 12276) in relation to the Cx43(GJA1) expression.

```{r}
##Generate Cx43 signature
Cx43.g <- cut(emc.msk.exp["GJA1",], breaks = quantile(emc.msk.exp["GJA1",], probs = seq(from = 0, to = 1, by = 1/2)), labels = c("low", "high"))
Cx43.g[is.na(Cx43.g)] = "low"
emc.msk.ann$Cx43.g <- Cx43.g

##Kaplan-Meier plots of the probability of bone, lung and brain metastasis-free survival
survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ Cx43.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ emc.msk.exp["GJA1",])
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ Cx43.g), col=c("#4DAF4A", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="GJA1 in Bone Metastasis", mark.time=T)
legend("topright", c("low", "high"), col=c("#4DAF4A",  "#E41A1C"), lty=1, bty = "n")

survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ Cx43.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ emc.msk.exp["GJA1",])
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ Cx43.g), col=c("#4DAF4A", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="GJA1 in Lung Metastasis", mark.time=T)
legend("topright", c("low", "high"), col=c("#4DAF4A",  "#E41A1C"), lty=1, bty = "n")

survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ Cx43.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ emc.msk.exp["GJA1",])
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ Cx43.g), col=c("#4DAF4A", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="GJA1 in Brain Metastasis", mark.time=T)
legend("topright", c("low", "high"), col=c("#4DAF4A",  "#E41A1C"), lty=1, bty = "n")
```
