# Figure S1

## Metastasis-free survival curve
This analysis is based on a combined Erasmus/MSKCC dataset (GSE2603, 5327, 2034, and 12276) in relation to the mcSig-predicted NFAT activity.

```{r}
##Generate NFAT 8-gene signature
NFATsig<-c("FAP","COL3A1","ASPN","MRC2","ANGPTL2","MGP","PTRF","TWIST1")
NFATsig<-NFATsig[NFATsig %in% rownames(emc.msk.exp)]
NFAT_sig <- apply(emc.msk.exp[NFATsig, ], 2, sum)
NFAT.g <- cut(NFAT_sig, breaks = quantile(NFAT_sig, probs = seq(from = 0, to = 1, by = 1/3)), labels = c("low", "med", "high"))
NFAT.g[is.na(NFAT.g)] = "low"
emc.msk.ann$NFAT.g <- NFAT.g

##Kaplan-Meier plots of the probability of bone, lung and brain metastasis-free survival
survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ NFAT.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ NFAT_sig)
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ NFAT.g), col=c("#4DAF4A", "#FF7F00", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="NFATsig in Bone Metastasis", mark.time=T)
legend("topright", c("low", "med", "high"), col=c("#4DAF4A", "#FF7F00", "#E41A1C"), lty=1, bty = "n")

survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ NFAT.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ NFAT_sig)
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ NFAT.g), col=c("#4DAF4A", "#FF7F00", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="NFATsig in Brain Metastasis", mark.time=T)
legend("topright", c("low", "med", "high"), col=c("#4DAF4A", "#FF7F00", "#E41A1C"), lty=1, bty = "n")

survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ NFAT.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ NFAT_sig)
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ NFAT.g), col=c("#4DAF4A", "#FF7F00", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="NFATsig in Lung Metastasis", mark.time=T)
legend("topright", c("low", "med", "high"), col=c("#4DAF4A", "#FF7F00", "#E41A1C"), lty=1, bty = "n")
```



# Figure S5

## Metastasis-free survival curve
This analysis is based on a combined Erasmus/MSKCC dataset (GSE2603, 5327, 2034, and 12276) in relation to the Cx43(GJA1) expression.

```{r}
##Generate Cx43 signature
Cx43.g <- cut(emc.msk.exp["GJA1",], breaks = quantile(emc.msk.exp["GJA1",], probs = seq(from = 0, to = 1, by = 1/2)), labels = c("low", "high"))
Cx43.g[is.na(Cx43.g)] = "low"
emc.msk.ann$Cx43.g <- Cx43.g

##Kaplan-Meier plots of the probability of bone, lung and brain metastasis-free survival
survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ Cx43.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ emc.msk.exp["GJA1",])
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$BM) ~ Cx43.g), col=c("#4DAF4A", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="GJA1 in Bone Metastasis", mark.time=T)
legend("topright", c("low", "high"), col=c("#4DAF4A",  "#E41A1C"), lty=1, bty = "n")

survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ Cx43.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ emc.msk.exp["GJA1",])
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$LM) ~ Cx43.g), col=c("#4DAF4A", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="GJA1 in Lung Metastasis", mark.time=T)
legend("topright", c("low", "high"), col=c("#4DAF4A",  "#E41A1C"), lty=1, bty = "n")

survdiff(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ Cx43.g)
coxph(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ emc.msk.exp["GJA1",])
plot(survfit(Surv(emc.msk.ann$MFS, emc.msk.ann$BrM) ~ Cx43.g), col=c("#4DAF4A", "#E41A1C"), lty=1, xlab = "Months", ylab = "Metastasis-Free Survival prob.", ylim=c(0, 1), main="GJA1 in Brain Metastasis", mark.time=T)
legend("topright", c("low", "high"), col=c("#4DAF4A",  "#E41A1C"), lty=1, bty = "n")
```
